application: boilerplate
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# low expiration for non cache busted assets
default_expiration: 300s

#builtins:
#- remote_api: on

# pagespeed:
#   enabled_rewriters:
#   - MinifyCss
#   disabled_rewriters:
#   -WebpOptimization
#   -ImageResize
#   -ImageConvertToJpeg
#   -InlinePreviewImages
#   -LazyloadImages
#   -ProxyCss
#   -MoveCssToHead

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /(channel.html)
  static_files: static/misc/\1
  upload: static/misc/.+
  expiration: 365d

- url: /(crossdomain.xml|humans.txt|robots.txt)
  static_files: static/misc/\1
  upload: static/misc/.+

- url: /(apple-touch-icon.+|favicon.ico)
  static_files: static/favicons/\1
  upload: static/favicons/.+
  expiration: 1d

# css
- url: /.*/css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)
  expiration: 365d
- url: /css
  static_dir: static/css

# img
- url: /.*/img/(.*)
  static_files: static/img/\1
  upload: static/img/(.*)
  expiration: 365d
- url: /img
  static_dir: static/img

# js
- url: /.*/js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)
  expiration: 365d
- url: /js
  static_dir: static/js

# fonts
#- url: /.*/fonts/(.*)
#  static_files: static/fonts/\1
#  upload: static/fonts/(.*)
#- url: /fonts
#  static_dir: static/fonts

- url: /admin|/admin/.*
  script: controllers.routes.app
  secure: always
  login: admin

- url: /.*
  script: controllers.routes.app
  secure: always
