application: boilerplate
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: 3600s

#builtins:
#- remote_api: on

#pagespeed:
#  domains_to_rewrite:
#  - http://example.appspot.com
#  - https://example.appspot.com
#  enabled_rewriters:
#  - ProxyCss
#  - ProxyJs
#  - ProxyImages
#  - ConvertMetaTags
#  - InlineCss
#  - CombineCss
#  - MoveCssToHead
#  - ImageRecompressPng
#  - ImageRecompressJpeg
#  - WebpOptimization
#  - JsOptimize
#  disabled_rewriters:
#  - ImageConvertToJpeg
#  - LazyloadImages

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /(channel.html|crossdomain.xml|humans.txt|robots.txt)
  static_files: static/misc/\1
  upload: static/misc/.+
  #expiration: 7d

- url: /(apple-touch-icon.+|favicon.ico)
  static_files: static/favicons/\1
  upload: static/favicons/.+
  #expiration: 7d

- url: /.*/css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)
- url: /css
  static_dir: static/css
- url: /.*/img/(.*)
  static_files: static/img/\1
  upload: static/img/(.*)
- url: /img
  static_dir: static/img
- url: /.*/js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)
- url: /js
  static_dir: static/js
#- url: /fonts
#  static_dir: static/fonts


- url: /api.*
  script: controllers.api.api_controller.app

- url: /admin.*
  script: controllers.admin.index_controller.app
  login: admin

- url: /.*
  script: controllers.default.index_controller.app




